/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ui.tests;

import browser_Selenium.ui.internal.Browser_SeleniumActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Browser_SeleniumActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
