/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Do Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DoLoop#getC <em>C</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DoLoop#getAdd <em>Add</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDoLoop()
 * @model
 * @generated
 */
public interface DoLoop extends Loop
{
  /**
   * Returns the value of the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' containment reference.
   * @see #setC(Condition)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDoLoop_C()
   * @model containment="true"
   * @generated
   */
  Condition getC();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DoLoop#getC <em>C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' containment reference.
   * @see #getC()
   * @generated
   */
  void setC(Condition value);

  /**
   * Returns the value of the '<em><b>Add</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.AddCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Add</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDoLoop_Add()
   * @model containment="true"
   * @generated
   */
  EList<AddCondition> getAdd();

} // DoLoop
