/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ProgramImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FUNC = 0;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__B = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.Browser_TaskImpl <em>Browser Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.Browser_TaskImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBrowser_Task()
   * @generated
   */
  int BROWSER_TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_TASK__OPERATIONS = 1;

  /**
   * The number of structural features of the '<em>Browser Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OperationImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 2;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ClickImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClick()
   * @generated
   */
  int CLICK = 4;

  /**
   * The feature id for the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__ELT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.GoImpl <em>Go</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.GoImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGo()
   * @generated
   */
  int GO = 5;

  /**
   * The feature id for the '<em><b>Link</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO__LINK = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FillImpl <em>Fill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FillImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFill()
   * @generated
   */
  int FILL = 6;

  /**
   * The feature id for the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__ELT = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Fillwith</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__FILLWITH = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SelectImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 7;

  /**
   * The feature id for the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__ELT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VerifyImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 8;

  /**
   * The feature id for the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__ELT = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Find</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__FIND = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.Apply_AllImpl <em>Apply All</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.Apply_AllImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getApply_All()
   * @generated
   */
  int APPLY_ALL = 9;

  /**
   * The feature id for the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLY_ALL__ELT = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLY_ALL__ACTIONS = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Apply All</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLY_ALL_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
   * @generated
   */
  int IF = 10;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COND = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Add</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ADD = OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__OPERATIONS = OPERATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Operationsbis</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__OPERATIONSBIS = OPERATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StoreImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStore()
   * @generated
   */
  int STORE = 11;

  /**
   * The feature id for the '<em><b>Vari</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__VARI = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>T</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__T = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CallFunctionImpl <em>Call Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CallFunctionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCallFunction()
   * @generated
   */
  int CALL_FUNCTION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_FUNCTION__NAME = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_FUNCTION__VARS = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Call Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_FUNCTION_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getType()
   * @generated
   */
  int TYPE = 13;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TEXT = 0;

  /**
   * The feature id for the '<em><b>Elts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__ELTS = 1;

  /**
   * The feature id for the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__ELT = 2;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__COND = 3;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StringTypeImpl <em>String Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StringTypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStringType()
   * @generated
   */
  int STRING_TYPE = 14;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE__TEXT = 0;

  /**
   * The feature id for the '<em><b>Elts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE__ELTS = 1;

  /**
   * The feature id for the '<em><b>Elt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE__ELT = 2;

  /**
   * The feature id for the '<em><b>Cond</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE__COND = 3;

  /**
   * The number of structural features of the '<em>String Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FuncVarImpl <em>Func Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FuncVarImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFuncVar()
   * @generated
   */
  int FUNC_VAR = 15;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNC_VAR__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNC_VAR__NAME = 1;

  /**
   * The number of structural features of the '<em>Func Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNC_VAR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunctionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__VARS = 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__OPERATIONS = 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopImpl <em>Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LoopImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoop()
   * @generated
   */
  int LOOP = 17;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__OPERATIONS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ForLoopImpl <em>For Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ForLoopImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getForLoop()
   * @generated
   */
  int FOR_LOOP = 18;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_LOOP__OPERATIONS = LOOP__OPERATIONS;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_LOOP__START = LOOP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_LOOP__END = LOOP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Step</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_LOOP__STEP = LOOP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>For Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_LOOP_FEATURE_COUNT = LOOP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WhileLoopImpl <em>While Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WhileLoopImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWhileLoop()
   * @generated
   */
  int WHILE_LOOP = 19;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_LOOP__OPERATIONS = LOOP__OPERATIONS;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_LOOP__C = LOOP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Add</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_LOOP__ADD = LOOP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_LOOP_FEATURE_COUNT = LOOP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DoLoopImpl <em>Do Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DoLoopImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoLoop()
   * @generated
   */
  int DO_LOOP = 20;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_LOOP__OPERATIONS = LOOP__OPERATIONS;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_LOOP__C = LOOP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Add</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_LOOP__ADD = LOOP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Do Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_LOOP_FEATURE_COUNT = LOOP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 21;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AddConditionImpl <em>Add Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AddConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAddCondition()
   * @generated
   */
  int ADD_CONDITION = 22;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_CONDITION__OP = 0;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_CONDITION__COND = 1;

  /**
   * The number of structural features of the '<em>Add Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ElementsImpl <em>Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ElementsImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getElements()
   * @generated
   */
  int ELEMENTS = 23;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTS__TYPE = 0;

  /**
   * The number of structural features of the '<em>Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ElementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 24;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__TYPE = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.EltTypeImpl <em>Elt Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.EltTypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEltType()
   * @generated
   */
  int ELT_TYPE = 25;

  /**
   * The number of structural features of the '<em>Elt Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELT_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TagImpl <em>Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TagImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTag()
   * @generated
   */
  int TAG = 26;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__HTML = ELT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tag</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__TAG = ELT_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG_FEATURE_COUNT = ELT_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SimpleOpImpl <em>Simple Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SimpleOpImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSimpleOp()
   * @generated
   */
  int SIMPLE_OP = 27;

  /**
   * The feature id for the '<em><b>Elt1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_OP__ELT1 = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_OP__OP = CONDITION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Elt2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_OP__ELT2 = CONDITION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Simple Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_OP_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComparableEltImpl <em>Comparable Elt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComparableEltImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComparableElt()
   * @generated
   */
  int COMPARABLE_ELT = 28;

  /**
   * The feature id for the '<em><b>Inte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARABLE_ELT__INTE = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARABLE_ELT__TEXT = 1;

  /**
   * The number of structural features of the '<em>Comparable Elt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARABLE_ELT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TextImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getText()
   * @generated
   */
  int TEXT = 29;

  /**
   * The feature id for the '<em><b>Vari</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__VARI = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__NAME = 1;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 30;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.myDsl.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Program#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Func</em>'.
   * @see org.xtext.example.mydsl.myDsl.Program#getFunc()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Func();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Program#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>B</em>'.
   * @see org.xtext.example.mydsl.myDsl.Program#getB()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_B();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Browser_Task <em>Browser Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browser Task</em>'.
   * @see org.xtext.example.mydsl.myDsl.Browser_Task
   * @generated
   */
  EClass getBrowser_Task();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Browser_Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Browser_Task#getName()
   * @see #getBrowser_Task()
   * @generated
   */
  EAttribute getBrowser_Task_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Browser_Task#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl.myDsl.Browser_Task#getOperations()
   * @see #getBrowser_Task()
   * @generated
   */
  EReference getBrowser_Task_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.myDsl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.example.mydsl.myDsl.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Click#getElt <em>Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Click#getElt()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Elt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Go <em>Go</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go</em>'.
   * @see org.xtext.example.mydsl.myDsl.Go
   * @generated
   */
  EClass getGo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Go#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Link</em>'.
   * @see org.xtext.example.mydsl.myDsl.Go#getLink()
   * @see #getGo()
   * @generated
   */
  EReference getGo_Link();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fill <em>Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fill
   * @generated
   */
  EClass getFill();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Fill#getElt <em>Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fill#getElt()
   * @see #getFill()
   * @generated
   */
  EReference getFill_Elt();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Fill#getFillwith <em>Fillwith</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fillwith</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fill#getFillwith()
   * @see #getFill()
   * @generated
   */
  EReference getFill_Fillwith();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.xtext.example.mydsl.myDsl.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Select#getElt <em>Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Select#getElt()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Elt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see org.xtext.example.mydsl.myDsl.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Verify#getElt <em>Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Verify#getElt()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Elt();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Verify#getFind <em>Find</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Find</em>'.
   * @see org.xtext.example.mydsl.myDsl.Verify#getFind()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Find();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Apply_All <em>Apply All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Apply All</em>'.
   * @see org.xtext.example.mydsl.myDsl.Apply_All
   * @generated
   */
  EClass getApply_All();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Apply_All#getElt <em>Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Apply_All#getElt()
   * @see #getApply_All()
   * @generated
   */
  EReference getApply_All_Elt();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Apply_All#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.mydsl.myDsl.Apply_All#getActions()
   * @see #getApply_All()
   * @generated
   */
  EReference getApply_All_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see org.xtext.example.mydsl.myDsl.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getCond()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Cond();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.If#getAdd <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Add</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getAdd()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Add();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.If#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getOperations()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Operations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.If#getOperationsbis <em>Operationsbis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operationsbis</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getOperationsbis()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Operationsbis();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see org.xtext.example.mydsl.myDsl.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Store#getVari <em>Vari</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vari</em>'.
   * @see org.xtext.example.mydsl.myDsl.Store#getVari()
   * @see #getStore()
   * @generated
   */
  EAttribute getStore_Vari();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Store#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>T</em>'.
   * @see org.xtext.example.mydsl.myDsl.Store#getT()
   * @see #getStore()
   * @generated
   */
  EReference getStore_T();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CallFunction <em>Call Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call Function</em>'.
   * @see org.xtext.example.mydsl.myDsl.CallFunction
   * @generated
   */
  EClass getCallFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CallFunction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.CallFunction#getName()
   * @see #getCallFunction()
   * @generated
   */
  EAttribute getCallFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.CallFunction#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see org.xtext.example.mydsl.myDsl.CallFunction#getVars()
   * @see #getCallFunction()
   * @generated
   */
  EReference getCallFunction_Vars();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Type#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type#getText()
   * @see #getType()
   * @generated
   */
  EReference getType_Text();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Type#getElts <em>Elts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elts</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type#getElts()
   * @see #getType()
   * @generated
   */
  EReference getType_Elts();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Type#getElt <em>Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type#getElt()
   * @see #getType()
   * @generated
   */
  EReference getType_Elt();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Type#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type#getCond()
   * @see #getType()
   * @generated
   */
  EReference getType_Cond();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.StringType <em>String Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringType
   * @generated
   */
  EClass getStringType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.StringType#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringType#getText()
   * @see #getStringType()
   * @generated
   */
  EAttribute getStringType_Text();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.StringType#getElts <em>Elts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Elts</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringType#getElts()
   * @see #getStringType()
   * @generated
   */
  EAttribute getStringType_Elts();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.StringType#getElt <em>Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringType#getElt()
   * @see #getStringType()
   * @generated
   */
  EAttribute getStringType_Elt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.StringType#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringType#getCond()
   * @see #getStringType()
   * @generated
   */
  EAttribute getStringType_Cond();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.FuncVar <em>Func Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Func Var</em>'.
   * @see org.xtext.example.mydsl.myDsl.FuncVar
   * @generated
   */
  EClass getFuncVar();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.FuncVar#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.FuncVar#getType()
   * @see #getFuncVar()
   * @generated
   */
  EReference getFuncVar_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.FuncVar#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.FuncVar#getName()
   * @see #getFuncVar()
   * @generated
   */
  EAttribute getFuncVar_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Function#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function#getVars()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Vars();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Function#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function#getOperations()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Loop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop</em>'.
   * @see org.xtext.example.mydsl.myDsl.Loop
   * @generated
   */
  EClass getLoop();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Loop#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl.myDsl.Loop#getOperations()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ForLoop <em>For Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Loop</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForLoop
   * @generated
   */
  EClass getForLoop();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ForLoop#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForLoop#getStart()
   * @see #getForLoop()
   * @generated
   */
  EAttribute getForLoop_Start();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ForLoop#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForLoop#getEnd()
   * @see #getForLoop()
   * @generated
   */
  EAttribute getForLoop_End();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ForLoop#getStep <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Step</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForLoop#getStep()
   * @see #getForLoop()
   * @generated
   */
  EAttribute getForLoop_Step();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.WhileLoop <em>While Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Loop</em>'.
   * @see org.xtext.example.mydsl.myDsl.WhileLoop
   * @generated
   */
  EClass getWhileLoop();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.WhileLoop#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>C</em>'.
   * @see org.xtext.example.mydsl.myDsl.WhileLoop#getC()
   * @see #getWhileLoop()
   * @generated
   */
  EReference getWhileLoop_C();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.WhileLoop#getAdd <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Add</em>'.
   * @see org.xtext.example.mydsl.myDsl.WhileLoop#getAdd()
   * @see #getWhileLoop()
   * @generated
   */
  EReference getWhileLoop_Add();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DoLoop <em>Do Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Do Loop</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoLoop
   * @generated
   */
  EClass getDoLoop();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.DoLoop#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>C</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoLoop#getC()
   * @see #getDoLoop()
   * @generated
   */
  EReference getDoLoop_C();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.DoLoop#getAdd <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Add</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoLoop#getAdd()
   * @see #getDoLoop()
   * @generated
   */
  EReference getDoLoop_Add();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AddCondition <em>Add Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.AddCondition
   * @generated
   */
  EClass getAddCondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.AddCondition#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.AddCondition#getOp()
   * @see #getAddCondition()
   * @generated
   */
  EAttribute getAddCondition_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.AddCondition#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.AddCondition#getCond()
   * @see #getAddCondition()
   * @generated
   */
  EReference getAddCondition_Cond();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Elements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.myDsl.Elements
   * @generated
   */
  EClass getElements();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Elements#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Elements#getType()
   * @see #getElements()
   * @generated
   */
  EReference getElements_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Element#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Element#getType()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.EltType <em>Elt Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elt Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.EltType
   * @generated
   */
  EClass getEltType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Tag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tag</em>'.
   * @see org.xtext.example.mydsl.myDsl.Tag
   * @generated
   */
  EClass getTag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Tag#getHtml <em>Html</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Html</em>'.
   * @see org.xtext.example.mydsl.myDsl.Tag#getHtml()
   * @see #getTag()
   * @generated
   */
  EAttribute getTag_Html();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Tag#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tag</em>'.
   * @see org.xtext.example.mydsl.myDsl.Tag#getTag()
   * @see #getTag()
   * @generated
   */
  EReference getTag_Tag();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SimpleOp <em>Simple Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.SimpleOp
   * @generated
   */
  EClass getSimpleOp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.SimpleOp#getElt1 <em>Elt1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt1</em>'.
   * @see org.xtext.example.mydsl.myDsl.SimpleOp#getElt1()
   * @see #getSimpleOp()
   * @generated
   */
  EReference getSimpleOp_Elt1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SimpleOp#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.SimpleOp#getOp()
   * @see #getSimpleOp()
   * @generated
   */
  EAttribute getSimpleOp_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.SimpleOp#getElt2 <em>Elt2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elt2</em>'.
   * @see org.xtext.example.mydsl.myDsl.SimpleOp#getElt2()
   * @see #getSimpleOp()
   * @generated
   */
  EReference getSimpleOp_Elt2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ComparableElt <em>Comparable Elt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparable Elt</em>'.
   * @see org.xtext.example.mydsl.myDsl.ComparableElt
   * @generated
   */
  EClass getComparableElt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ComparableElt#getInte <em>Inte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Inte</em>'.
   * @see org.xtext.example.mydsl.myDsl.ComparableElt#getInte()
   * @see #getComparableElt()
   * @generated
   */
  EAttribute getComparableElt_Inte();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ComparableElt#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.ComparableElt#getText()
   * @see #getComparableElt()
   * @generated
   */
  EReference getComparableElt_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Text#getVari <em>Vari</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vari</em>'.
   * @see org.xtext.example.mydsl.myDsl.Text#getVari()
   * @see #getText()
   * @generated
   */
  EReference getText_Vari();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Text#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Text#getName()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ProgramImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FUNC = eINSTANCE.getProgram_Func();

    /**
     * The meta object literal for the '<em><b>B</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__B = eINSTANCE.getProgram_B();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.Browser_TaskImpl <em>Browser Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.Browser_TaskImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBrowser_Task()
     * @generated
     */
    EClass BROWSER_TASK = eINSTANCE.getBrowser_Task();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROWSER_TASK__NAME = eINSTANCE.getBrowser_Task_Name();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BROWSER_TASK__OPERATIONS = eINSTANCE.getBrowser_Task_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OperationImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ClickImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Elt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__ELT = eINSTANCE.getClick_Elt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.GoImpl <em>Go</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.GoImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGo()
     * @generated
     */
    EClass GO = eINSTANCE.getGo();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GO__LINK = eINSTANCE.getGo_Link();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FillImpl <em>Fill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FillImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFill()
     * @generated
     */
    EClass FILL = eINSTANCE.getFill();

    /**
     * The meta object literal for the '<em><b>Elt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL__ELT = eINSTANCE.getFill_Elt();

    /**
     * The meta object literal for the '<em><b>Fillwith</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL__FILLWITH = eINSTANCE.getFill_Fillwith();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SelectImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Elt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__ELT = eINSTANCE.getSelect_Elt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VerifyImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '<em><b>Elt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__ELT = eINSTANCE.getVerify_Elt();

    /**
     * The meta object literal for the '<em><b>Find</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__FIND = eINSTANCE.getVerify_Find();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.Apply_AllImpl <em>Apply All</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.Apply_AllImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getApply_All()
     * @generated
     */
    EClass APPLY_ALL = eINSTANCE.getApply_All();

    /**
     * The meta object literal for the '<em><b>Elt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLY_ALL__ELT = eINSTANCE.getApply_All_Elt();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLY_ALL__ACTIONS = eINSTANCE.getApply_All_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COND = eINSTANCE.getIf_Cond();

    /**
     * The meta object literal for the '<em><b>Add</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ADD = eINSTANCE.getIf_Add();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__OPERATIONS = eINSTANCE.getIf_Operations();

    /**
     * The meta object literal for the '<em><b>Operationsbis</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__OPERATIONSBIS = eINSTANCE.getIf_Operationsbis();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StoreImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '<em><b>Vari</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE__VARI = eINSTANCE.getStore_Vari();

    /**
     * The meta object literal for the '<em><b>T</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE__T = eINSTANCE.getStore_T();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CallFunctionImpl <em>Call Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CallFunctionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCallFunction()
     * @generated
     */
    EClass CALL_FUNCTION = eINSTANCE.getCallFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALL_FUNCTION__NAME = eINSTANCE.getCallFunction_Name();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALL_FUNCTION__VARS = eINSTANCE.getCallFunction_Vars();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__TEXT = eINSTANCE.getType_Text();

    /**
     * The meta object literal for the '<em><b>Elts</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__ELTS = eINSTANCE.getType_Elts();

    /**
     * The meta object literal for the '<em><b>Elt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__ELT = eINSTANCE.getType_Elt();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__COND = eINSTANCE.getType_Cond();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StringTypeImpl <em>String Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StringTypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStringType()
     * @generated
     */
    EClass STRING_TYPE = eINSTANCE.getStringType();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_TYPE__TEXT = eINSTANCE.getStringType_Text();

    /**
     * The meta object literal for the '<em><b>Elts</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_TYPE__ELTS = eINSTANCE.getStringType_Elts();

    /**
     * The meta object literal for the '<em><b>Elt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_TYPE__ELT = eINSTANCE.getStringType_Elt();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_TYPE__COND = eINSTANCE.getStringType_Cond();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FuncVarImpl <em>Func Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FuncVarImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFuncVar()
     * @generated
     */
    EClass FUNC_VAR = eINSTANCE.getFuncVar();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNC_VAR__TYPE = eINSTANCE.getFuncVar_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNC_VAR__NAME = eINSTANCE.getFuncVar_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunctionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__VARS = eINSTANCE.getFunction_Vars();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__OPERATIONS = eINSTANCE.getFunction_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopImpl <em>Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LoopImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoop()
     * @generated
     */
    EClass LOOP = eINSTANCE.getLoop();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__OPERATIONS = eINSTANCE.getLoop_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ForLoopImpl <em>For Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ForLoopImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getForLoop()
     * @generated
     */
    EClass FOR_LOOP = eINSTANCE.getForLoop();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR_LOOP__START = eINSTANCE.getForLoop_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR_LOOP__END = eINSTANCE.getForLoop_End();

    /**
     * The meta object literal for the '<em><b>Step</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR_LOOP__STEP = eINSTANCE.getForLoop_Step();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WhileLoopImpl <em>While Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WhileLoopImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWhileLoop()
     * @generated
     */
    EClass WHILE_LOOP = eINSTANCE.getWhileLoop();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_LOOP__C = eINSTANCE.getWhileLoop_C();

    /**
     * The meta object literal for the '<em><b>Add</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_LOOP__ADD = eINSTANCE.getWhileLoop_Add();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DoLoopImpl <em>Do Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DoLoopImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoLoop()
     * @generated
     */
    EClass DO_LOOP = eINSTANCE.getDoLoop();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DO_LOOP__C = eINSTANCE.getDoLoop_C();

    /**
     * The meta object literal for the '<em><b>Add</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DO_LOOP__ADD = eINSTANCE.getDoLoop_Add();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AddConditionImpl <em>Add Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AddConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAddCondition()
     * @generated
     */
    EClass ADD_CONDITION = eINSTANCE.getAddCondition();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_CONDITION__OP = eINSTANCE.getAddCondition_Op();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_CONDITION__COND = eINSTANCE.getAddCondition_Cond();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ElementsImpl <em>Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ElementsImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getElements()
     * @generated
     */
    EClass ELEMENTS = eINSTANCE.getElements();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENTS__TYPE = eINSTANCE.getElements_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ElementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__TYPE = eINSTANCE.getElement_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.EltTypeImpl <em>Elt Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.EltTypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEltType()
     * @generated
     */
    EClass ELT_TYPE = eINSTANCE.getEltType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TagImpl <em>Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TagImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTag()
     * @generated
     */
    EClass TAG = eINSTANCE.getTag();

    /**
     * The meta object literal for the '<em><b>Html</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG__HTML = eINSTANCE.getTag_Html();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAG__TAG = eINSTANCE.getTag_Tag();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SimpleOpImpl <em>Simple Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SimpleOpImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSimpleOp()
     * @generated
     */
    EClass SIMPLE_OP = eINSTANCE.getSimpleOp();

    /**
     * The meta object literal for the '<em><b>Elt1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_OP__ELT1 = eINSTANCE.getSimpleOp_Elt1();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_OP__OP = eINSTANCE.getSimpleOp_Op();

    /**
     * The meta object literal for the '<em><b>Elt2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_OP__ELT2 = eINSTANCE.getSimpleOp_Elt2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComparableEltImpl <em>Comparable Elt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComparableEltImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComparableElt()
     * @generated
     */
    EClass COMPARABLE_ELT = eINSTANCE.getComparableElt();

    /**
     * The meta object literal for the '<em><b>Inte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARABLE_ELT__INTE = eINSTANCE.getComparableElt_Inte();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARABLE_ELT__TEXT = eINSTANCE.getComparableElt_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TextImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Vari</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT__VARI = eINSTANCE.getText_Vari();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__NAME = eINSTANCE.getText_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

  }

} //MyDslPackage
