/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SimpleOp#getElt1 <em>Elt1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SimpleOp#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SimpleOp#getElt2 <em>Elt2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSimpleOp()
 * @model
 * @generated
 */
public interface SimpleOp extends Condition
{
  /**
   * Returns the value of the '<em><b>Elt1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elt1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elt1</em>' containment reference.
   * @see #setElt1(ComparableElt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSimpleOp_Elt1()
   * @model containment="true"
   * @generated
   */
  ComparableElt getElt1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SimpleOp#getElt1 <em>Elt1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elt1</em>' containment reference.
   * @see #getElt1()
   * @generated
   */
  void setElt1(ComparableElt value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSimpleOp_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SimpleOp#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Elt2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elt2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elt2</em>' containment reference.
   * @see #setElt2(ComparableElt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSimpleOp_Elt2()
   * @model containment="true"
   * @generated
   */
  ComparableElt getElt2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SimpleOp#getElt2 <em>Elt2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elt2</em>' containment reference.
   * @see #getElt2()
   * @generated
   */
  void setElt2(ComparableElt value);

} // SimpleOp
