/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Store</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Store#getVari <em>Vari</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Store#getText <em>Text</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Store#getElts <em>Elts</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Store#getElt <em>Elt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Store#getCond <em>Cond</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStore()
 * @model
 * @generated
 */
public interface Store extends Operation
{
  /**
   * Returns the value of the '<em><b>Vari</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vari</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vari</em>' attribute.
   * @see #setVari(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStore_Vari()
   * @model
   * @generated
   */
  String getVari();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Store#getVari <em>Vari</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vari</em>' attribute.
   * @see #getVari()
   * @generated
   */
  void setVari(String value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(Text)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStore_Text()
   * @model containment="true"
   * @generated
   */
  Text getText();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Store#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(Text value);

  /**
   * Returns the value of the '<em><b>Elts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elts</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elts</em>' containment reference.
   * @see #setElts(Elements)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStore_Elts()
   * @model containment="true"
   * @generated
   */
  Elements getElts();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Store#getElts <em>Elts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elts</em>' containment reference.
   * @see #getElts()
   * @generated
   */
  void setElts(Elements value);

  /**
   * Returns the value of the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elt</em>' containment reference.
   * @see #setElt(Element)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStore_Elt()
   * @model containment="true"
   * @generated
   */
  Element getElt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Store#getElt <em>Elt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elt</em>' containment reference.
   * @see #getElt()
   * @generated
   */
  void setElt(Element value);

  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cond</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Condition)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStore_Cond()
   * @model containment="true"
   * @generated
   */
  Condition getCond();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Store#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Condition value);

} // Store
