/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Tag#getHtml <em>Html</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Tag#getTag <em>Tag</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTag()
 * @model
 * @generated
 */
public interface Tag extends EltType
{
  /**
   * Returns the value of the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Html</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Html</em>' attribute.
   * @see #setHtml(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTag_Html()
   * @model
   * @generated
   */
  String getHtml();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Tag#getHtml <em>Html</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Html</em>' attribute.
   * @see #getHtml()
   * @generated
   */
  void setHtml(String value);

  /**
   * Returns the value of the '<em><b>Tag</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tag</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tag</em>' containment reference.
   * @see #setTag(Text)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTag_Tag()
   * @model containment="true"
   * @generated
   */
  Text getTag();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Tag#getTag <em>Tag</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tag</em>' containment reference.
   * @see #getTag()
   * @generated
   */
  void setTag(Text value);

} // Tag
