/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verify</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Verify#getElt <em>Elt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Verify#getFind <em>Find</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerify()
 * @model
 * @generated
 */
public interface Verify extends Action, Condition
{
  /**
   * Returns the value of the '<em><b>Elt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elt</em>' containment reference.
   * @see #setElt(Element)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerify_Elt()
   * @model containment="true"
   * @generated
   */
  Element getElt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Verify#getElt <em>Elt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elt</em>' containment reference.
   * @see #getElt()
   * @generated
   */
  void setElt(Element value);

  /**
   * Returns the value of the '<em><b>Find</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Find</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Find</em>' containment reference.
   * @see #setFind(Text)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerify_Find()
   * @model containment="true"
   * @generated
   */
  Text getFind();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Verify#getFind <em>Find</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Find</em>' containment reference.
   * @see #getFind()
   * @generated
   */
  void setFind(Text value);

} // Verify
